version: "3.6"
services:
  django:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./django.Dockerfile
    volumes:
      - ./docker/media/:/app/media/
      - ./docker/static/:/app/static/

    environment:
      - SECRET_KEY=secret
      - DEBUG=True
    env_file:
      - ./.env

  nginx:
    build:
      context: ./
      dockerfile: ./nginx.Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/static/:/app/djangostatic/
    ports:
      - 80:8080
    restart: unless-stopped
  postgres:
    restart: unless-stopped
    image: postgres:13.4-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    ports:
      - 5432
    env_file:
      - ./.env


volumes:
  local_postgres_data_backups:
  local_postgres_data:
