# Generated by Django 3.2.7 on 2021-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20211115_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorimages',
            name='image',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Image SVG'),
        ),
    ]
