version: 2
jobs:
  build:
    machine:
      - image: ubuntu-20.04
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build --pull -t "volodyabravo/globalmaps:backend" -f ./nginx.Dockerfile .
          docker push "volodyabravo/globalmaps:backend"
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build --pull -t "volodyabravo/globalmaps:frontend" -f ./nginx.Dockerfile .
          docker push "volodyabravo/globalmaps:frontend"

workflows:
  version: 2
  production: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
