version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t "volodyabravo/globalmaps:backend" -f ./django.Dockerfile .
          docker push "volodyabravo/globalmaps:backend"
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t "volodyabravo/globalmaps:frontend" -f ./nginx.Dockerfile .
          docker push "volodyabravo/globalmaps:frontend"
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t "volodyabravo/globalmaps:puppet" -f ./puppet.Dockerfile .
          docker push "volodyabravo/globalmaps:puppet"

workflows:
  version: 2
  production: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
