# Generated by Django 3.2.7 on 2021-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Error')], default=0, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date and time')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='User map data')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is this size active')),
                ('order', models.IntegerField(default=1, verbose_name='Size position in themes list')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('width', models.PositiveIntegerField(verbose_name='Width')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is this theme active')),
                ('order', models.IntegerField(default=1, verbose_name='Theme position in themes list')),
                ('product', models.IntegerField(choices=[(1, 'Sky map'), (2, 'Street map')], default=0, verbose_name='Type')),
                ('name', models.CharField(max_length=500, verbose_name='Theme name')),
                ('preview', models.ImageField(blank=True, upload_to='uploads/images/', verbose_name='Theme preview image')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Theme JSON data')),
            ],
        ),
    ]
