# Generated by Django 3.2.7 on 2021-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images/generated/', verbose_name='Generated image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Generated'), (3, 'Error')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='preview',
            field=models.ImageField(blank=True, upload_to='uploads/images/preview/', verbose_name='Theme preview image'),
        ),
    ]
