# Generated by Django 3.2.7 on 2021-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211009_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsize',
            name='units',
            field=models.IntegerField(choices=[(1, 'px'), (2, 'cm')], default=1, verbose_name='Map size units'),
        ),
        migrations.AddField(
            model_name='mapsize',
            name='version',
            field=models.IntegerField(choices=[(1, 'Web version'), (2, 'Print version')], default=1, verbose_name='Map Producing Version'),
        ),
        migrations.AlterField(
            model_name='maporder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Generated'), (3, 'Error')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='maptheme',
            name='product',
            field=models.IntegerField(choices=[(1, 'Sky map'), (2, 'Street map')], default=1, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='mapversions',
            name='version',
            field=models.IntegerField(choices=[(1, 'Web version'), (2, 'Print version')], default=1, verbose_name='Map Producing Version'),
        ),
    ]
