# Generated by Django 3.2.7 on 2021-10-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211019_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapprices',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mapsize',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mapsize',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='mapversions',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mapversions',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='mapprices',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.mapsize'),
        ),
        migrations.AddField(
            model_name='mapprices',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.mapversions'),
        ),
        migrations.AddField(
            model_name='maptheme',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images/static/', verbose_name='Image'),
        ),
    ]
