# Generated by Django 3.2.7 on 2021-11-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20211024_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsize',
            name='height_px',
            field=models.PositiveIntegerField(default=0, verbose_name='Height in px upon render'),
        ),
        migrations.AddField(
            model_name='mapsize',
            name='scale',
            field=models.PositiveIntegerField(default=1, verbose_name='Scale upon render'),
        ),
        migrations.AddField(
            model_name='mapsize',
            name='width_px',
            field=models.PositiveIntegerField(default=0, verbose_name='Width in px upon render'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(43263424, 'Заказ'), (43263229, 'Оплачено'), (43263232, 'Печать'), (43263235, 'На упаковку'), (43263238, 'Упаковка'), (43263427, 'На доставку'), (43263430, 'Доставка'), (43263433, 'Самовывоз'), (142, 'Успешно реализовано'), (143, 'Закрыто и не реализовано')], default=1, verbose_name='Status'),
        ),
    ]
