# Generated by Django 3.2.7 on 2021-11-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20211105_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapversions',
            name='version',
        ),
        migrations.AddField(
            model_name='mapversions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.mapversions'),
        ),
        migrations.AlterField(
            model_name='mapsize',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.mapversions'),
        ),
    ]
