# Generated by Django 3.2.7 on 2021-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20211126_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Delivery'),
        ),
    ]
