# Generated by Django 3.2.7 on 2021-11-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsize',
            name='version',
        ),
        migrations.AddField(
            model_name='mapsize',
            name='depth',
            field=models.PositiveIntegerField(default=5, verbose_name='Depth'),
        ),
    ]
