# Generated by Django 3.2.7 on 2021-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20211126_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.IntegerField(blank=True, null=True, verbose_name='Track number'),
        ),
    ]
