# Generated by Django 3.2.7 on 2021-12-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20211201_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maporder',
            name='data',
        ),
        migrations.AddField(
            model_name='maporder',
            name='divider',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='divider'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='exception_text',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='subline'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='headline',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='headline'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.mapsize'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='subline',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='subline'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='tagline',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.maptheme'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='x',
            field=models.IntegerField(blank=True, null=True, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='y',
            field=models.IntegerField(blank=True, null=True, verbose_name='y'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='zoom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zoom'),
        ),
        migrations.AddField(
            model_name='order',
            name='exception_text',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='subline'),
        ),
    ]
