# Generated by Django 3.2.7 on 2021-12-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20211202_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapversions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='catalog.mapversions'),
        ),
    ]
