# Generated by Django 3.2.7 on 2021-12-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_mapversions_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapversions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.mapversions'),
        ),
    ]
