# Generated by Django 3.2.7 on 2021-12-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_mapversions_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_city_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_city_name'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_region',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_region'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_type_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_type_name'),
        ),
        migrations.AddField(
            model_name='order',
            name='pvz_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='pvz_id'),
        ),
    ]
