# Generated by Django 3.2.7 on 2021-12-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20211204_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(43263424, 'Заказ'), (43263229, 'Оплачено'), (43263232, 'Печать'), (43263235, 'На упаковку'), (43263238, 'Упаковка'), (43263427, 'На доставку'), (43263430, 'Доставка'), (43263433, 'Самовывоз'), (142, 'Успешно реализовано'), (143, 'Закрыто и не реализовано')], default=43263424, verbose_name='Status'),
        ),
    ]
