# Generated by Django 3.2.7 on 2021-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_order_exception_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exception_text',
        ),
        migrations.AddField(
            model_name='order',
            name='call_back',
            field=models.BooleanField(default=False, verbose_name='Call back'),
        ),
        migrations.AddField(
            model_name='order',
            name='emails_agree',
            field=models.BooleanField(default=False, verbose_name='emails_agree'),
        ),
    ]
