# Generated by Django 3.2.7 on 2021-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20211204_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapprices',
            name='weight',
            field=models.PositiveIntegerField(default=800, verbose_name='Weight in grams'),
        ),
    ]
