# Generated by Django 3.2.7 on 2021-12-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_mapprices_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversions',
            name='needs_delivery',
            field=models.BooleanField(default=True, verbose_name='Needs delivery'),
        ),
    ]
