# Generated by Django 3.2.7 on 2021-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_mapversions_needs_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapprices',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='mapprices',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
