# Generated by Django 3.2.7 on 2021-12-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20211205_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorimages',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
    ]
