# Generated by Django 3.2.7 on 2021-12-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_vectorimages_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maporder',
            name='x',
        ),
        migrations.RemoveField(
            model_name='maporder',
            name='y',
        ),
        migrations.AddField(
            model_name='maporder',
            name='city_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='cityName'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and time'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='lng'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='orientation',
            field=models.IntegerField(choices=[(1, 'portrait'), (2, 'landscape')], default=2, verbose_name='Orientation'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='vector_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.vectorcolors'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='vector_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.vectorimages'),
        ),
        migrations.AddField(
            model_name='maporder',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.mapversions'),
        ),
        migrations.AlterField(
            model_name='maporder',
            name='date',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
    ]
