# Generated by Django 3.2.7 on 2021-12-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_maporder_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='maporder',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
