# Generated by Django 3.2.7 on 2021-12-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20211208_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='maporder',
            name='product',
            field=models.IntegerField(choices=[(1, 'Sky map'), (2, 'Street map'), (3, 'Vector image')], default=1, verbose_name='Map'),
        ),
    ]
