# Generated by Django 3.2.7 on 2021-12-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_maporder_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maporder',
            old_name='total_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
