# Generated by Django 3.2.7 on 2021-12-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20211208_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maporder',
            name='exception_text',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Exception'),
        ),
    ]
