# Generated by Django 3.2.7 on 2021-12-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20211213_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payment id'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment url'),
        ),
        migrations.AlterField(
            model_name='maporder',
            name='product',
            field=models.IntegerField(choices=[(1, 'Интерьерная звездная карта'), (2, 'Интерьерная городская карта'), (3, 'Интерьерная векторная карта')], default=1, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='maptheme',
            name='product',
            field=models.IntegerField(choices=[(1, 'Интерьерная звездная карта'), (2, 'Интерьерная городская карта'), (3, 'Интерьерная векторная карта')], default=1, verbose_name='Map'),
        ),
    ]
