# Generated by Django 3.2.7 on 2021-12-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20211217_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversions',
            name='sizes',
            field=models.ManyToManyField(to='catalog.MapSize'),
        ),
    ]
