# Generated by Django 3.2.7 on 2021-12-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20211225_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsize',
            name='versions',
        ),
        migrations.AddField(
            model_name='mapversions',
            name='sizes',
            field=models.ManyToManyField(to='catalog.MapSize'),
        ),
    ]
