# Generated by Django 3.2.7 on 2021-12-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20211225_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='New', max_length=500, null=True, verbose_name='Payment status'),
        ),
    ]
