# Generated by Django 3.2.7 on 2021-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_mapversions_bottompic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversions',
            name='children_description',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
    ]
