# Generated by Django 3.2.7 on 2021-12-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_mapversions_children_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversions',
            name='custom_css',
            field=models.CharField(blank=True, default='', max_length=50000, null=True, verbose_name='Custom css'),
        ),
    ]
