import { Geometry } from "geojson";
import { PVZ } from "../api/themes";

export const pvzs: {
  [key: string]: PVZ;
} = {
  MKHCH11: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH11",
    address: "ул. Юсупа Акаева, 23",
    address_description: "",
    city: "Махачкала",
    longitude: 47.506595,
    latitude: 42.95208,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79280050538",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH10: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH10",
    address: "ул. Магомедтагирова, 26",
    address_description: "Напротив сквера Депутатов",
    city: "Махачкала",
    longitude: 47.456748,
    latitude: 42.998953,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79285959919",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH9: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH9",
    address: "ул. С.Асиятилова, 22",
    address_description: "Напротив Научной библиотеки им. А.А.Абилова.",
    city: "Махачкала",
    longitude: 47.494567,
    latitude: 42.980897,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79288339919",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH16: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH16",
    address: "ул. Айвазовского, 2",
    address_description: "Офис находиться напротив Северного Автовокзала",
    city: "Махачкала",
    longitude: 47.417267,
    latitude: 42.970495,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79280639919",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH15: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH15",
    address: "ул. Батырмурзаева, 94",
    address_description:
      "ул. Батырмурзаева, напротив мебельного салон Европа, район Узбекгородок",
    city: "Махачкала",
    longitude: 47.484119,
    latitude: 42.975415,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79882060011",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH3: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH3",
    address: "ул. Азиза Алиева, 23",
    address_description:
      "Пересечение Ярагского и Азиза Алиева (рядом стоматологический институт,магазин PORSCHE)",
    city: "Махачкала",
    longitude: 47.494028,
    latitude: 42.962538,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79882650101, +79285770099",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH8: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH8",
    address: "ул. Ирчи Казака, 1Д",
    address_description: "Напротив Музей «Россия - моя история»",
    city: "Махачкала",
    longitude: 47.49604,
    latitude: 42.969597,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79288715919",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH1: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH1",
    address: "ул. Гаруна Курбанова, 44А",
    address_description:
      "угол Коркмасова (Советская) и Гаруна Курбанова (Леваневского) Ресторан Ottoman palace - 50 метров",
    city: "Махачкала",
    longitude: 47.507035,
    latitude: 42.976398,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79882050066",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH13: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH13",
    address: "На ПЕТРА ПЕРВОГО, 71",
    address_description: "",
    city: "Махачкала",
    longitude: 47.53802,
    latitude: 42.968959,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79285169919",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH19: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH19",
    address: "пр-т Насрутдинова, 23/1",
    address_description: "Рядом Находится Магазин Фруктовый Сад",
    city: "Махачкала",
    longitude: 47.556532,
    latitude: 42.956023,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79285303888",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH7: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH7",
    address: "проспект Гамидова, 20",
    address_description:
      "Как добраться до офиса (кратко не больше 10 слов) Напротив магазина GrandCity.",
    city: "Махачкала",
    longitude: 47.510808,
    latitude: 42.960975,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79289589919",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH17: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH17",
    address: "пр-т Расула Гамзатова, 93",
    address_description: "ТЦ Фестиваль",
    city: "Махачкала",
    longitude: 47.515821,
    latitude: 42.977856,
    metro_id: null,
    type: "postamat",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+78007753553",
    postalcode: null,
    schedule: "Пн-Вс 10:00-22:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH18: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH18",
    address: "ул. Шамиля, 31",
    address_description: "ТЦ Центральный",
    city: "Махачкала",
    longitude: 47.494169,
    latitude: 42.968099,
    metro_id: null,
    type: "postamat",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+78007753553",
    postalcode: null,
    schedule: "Пн-Вс 09:00-21:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH14: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH14",
    address: "пр-т. Акушинского, 27Р",
    address_description:
      "От остановки (Финансовый колледж)  пройти в сторону троллейбусного кольца 110 метров офис СДЭКа справа от вас",
    city: "Махачкала",
    longitude: 47.434874,
    latitude: 42.975025,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79898969898",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
  MKHCH4: {
    delivery_method_id: "sdek_posylka_ss",
    delivery_method_name: "Посылка склад-склад СДЭК",
    id: "MKHCH4",
    address: "ул. Акушинского, 21",
    address_description:
      "Здание бывшего МГОУ. Стоматологическая клиника ЗУБ и Киргу диджитал рядом",
    city: "Махачкала",
    longitude: 47.46441,
    latitude: 42.981332,
    metro_id: null,
    type: "pvz",
    delivery_days: 5,
    delivery_price: 525,
    phone: "+79285789919",
    postalcode: null,
    schedule: "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
    payments: { online: true, cash: true, card: true },
  },
};

export function pvztoarray(pvzs: {
  [key: string]: PVZ
}): Array<PVZ> {
  let props = Object.entries(pvzs)
  let array: Array<PVZ> = props.map((prop) => prop[1])
  return array;
}

export type PVZGeoJSON = GeoJSON.FeatureCollection<Geometry, {
  id: string | null;
}>

export function pvzstofeatures(pvzs: Array<PVZ>) {
  let json: PVZGeoJSON  = {
    "features": [],
    "type": "FeatureCollection"
  }

  let features: PVZGeoJSON["features"] = pvzs.map((pvz) => {
    return {
      type: "Feature",
      properties: {
        title: pvz.address,
        description: pvz.address_description,
        id: pvz.id
      },
      geometry: {
        coordinates: [pvz.longitude, pvz.latitude],
        type: "Point",
      },
      
    }
  })

  json.features = features;


  return json;
}
