# Generated by Django 3.2.7 on 2021-11-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20211114_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='card_data',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(choices=[(1, 'Самовывоз'), (2, 'Курьер'), (3, 'Доставка')], default=1, verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Surname'),
        ),
    ]
